describe('Signup Account', () => {
    before('url',()=>{
        cy.visit('/')
    })
    it('Signup ',() => {
        cy.visit('/login')
        let a="username"+Math.random()
        //let b=Math.random
        cy.get('[data-qa="signup-name"]').type(a)
        cy.get('[data-qa="signup-email"]').type(a+"@gmail.com")
        cy.get('[data-qa="signup-button"]').click()
        cy.wait(2000)
        cy.get('[id="id_gender2"]').check()
      //  cy.get('[data-qa="name"]').contains(a)
       // cy.get('[data-qa="email"]').contains(a+"@gmail.com")
        cy.get('[data-qa="password"]').type("Sundu")
        cy.get('[data-qa="days"]').select(1)
        cy.get('[data-qa="months"]').select(5)
        cy.get('[data-qa="years"]').select(9)
        cy.get('[name="optin"]').check()
        cy.get('[data-qa="first_name"]').type("Sundari")
        cy.get('[data-qa="last_name"]').type("Sundu")
        cy.get('[data-qa="company"]').type("CTS")
        cy.get('[data-qa="address"]').type("siruseri")
        cy.get('[data-qa="address2"]').type("chennai")
        cy.get('[data-qa="country"]').select("India")
        cy.get('[data-qa="state"]').type("TamilNadu")
        cy.get('[data-qa="city"]').type("Chennai")
        cy.get('[data-qa="zipcode"]').type("622103")
        cy.get('[data-qa="mobile_number"]').type("987654321")
        cy.get('[data-qa="create-account"]').click()

    })
})